# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    rcel.book_library:
        class: RCel\BookReader\Infrastructure\InMemoryBookShelf

    rcel.book_reader:
        class: RCel\BookReader\Application\BookService
        arguments:
            - '@rcel.book_library'

    buzz:
        class: Buzz\Browser

    stopwatch:
        class: Symfony\Component\Stopwatch\Stopwatch

    rcel.open_weather_client_watch2:
        class: RCel\WeatherApi\OpenWeatherClientWatch2
        arguments:
            - '@buzz'
            - '@stopwatch'
